{inputs, pkgs, config, ...}: {
 environment.systemPackages = with pkgs; [
    neovim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    linuxHeaders
    wget
    curl
    firefox
    kitty
    alacritty
    git
    binutils
    gcc
    rustup
    egl-wayland
    wl-clipboard
    wl-clipboard-rs
    xwayland
    wayland-protocols
    zsh
    btop
    cava
    gnumake
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    file
    rofi
    kdePackages.dolphin
    mako
    pkgs.gh
    pipewire
    wireplumber
    hyprpolkitagent
    pkgs.kdePackages.qtwayland
    inputs.quickshell.packages.${pkgs.system}.default
    pkgs.nerd-fonts._0xproto
    pkgs.nerd-fonts.jetbrains-mono
    hyprshot
    satty
    zsh-powerlevel10k
    pkgs.unixtools.whereis
    discordo
    zoxide
    fish
    python3
    wayfarer
    pamixer
    gnupg
    pinentry-curses
    yazi
    cron
    spotify
    vinegar
    obsidian
    ydotool
    material-symbols
    ibm-plex
    brightnessctl
    imagemagick
    kdePackages.qt6ct
    papirus-icon-theme
    darkly-qt5
    darkly
    doas
    pinentry-rofi
    arrpc
    protonmail-desktop
    tor-browser
    protonvpn-cli
    protonvpn-gui
    deluge
    wine64Packages.unstableFull
    tor
    libc
    glibc
    tinycc
    openjdk21
    gradle
    gimp
    xdg-utils
    flatpak-xdg-utils
    ncurses
  ] ++ (with pkgs.python313Packages; [
    aubio
    pyaudio
    numpy
    pip
 ]);
}
